#!/usr/bin/env python3
"""
PSMILES to SMILES Storage Utility

This module handles the conversion of PSMILES to full SMILES strings during generation
and ensures they are stored together for efficient MD simulation workflows.
"""

import streamlit as st
from typing import Dict, Optional, Any, List
from datetime import datetime
import traceback

# Import the converter
try:
    from utils.psmiles_to_smiles_converter import PSMILESConverter
    CONVERTER_AVAILABLE = True
except ImportError:
    CONVERTER_AVAILABLE = False


class PSMILESWithSMILESStorage:
    """Utility class to handle PSMILES generation with SMILES storage"""
    
    def __init__(self):
        if CONVERTER_AVAILABLE:
            self.converter = PSMILESConverter()
            print(f"🧬 PSMILESWithSMILESStorage: Converter available and initialized")
        else:
            self.converter = None
            print(f"❌ PSMILESWithSMILESStorage: Converter not available - SMILES conversion will fail")
        
    def convert_and_store_psmiles(self, psmiles: str) -> Dict[str, Any]:
        """
        Convert PSMILES to SMILES, prioritizing stored polymer chain SMILES.
        
        This method first checks for polymer chain SMILES generated by DirectPolymerBuilder.
        If found, it uses that. Otherwise, falls back to monomer conversion.
        
        Args:
            psmiles: PSMILES string to convert
            
        Returns:
            Dict containing both PSMILES and SMILES with conversion metadata
        """
        result = {
            'psmiles': psmiles,
            'smiles': None,
            'smiles_conversion_success': False,
            'smiles_conversion_method': None,
            'smiles_conversion_error': None,
            'conversion_metadata': {}
        }
        
        # **PRIORITY 1: Check for stored polymer chain SMILES**
        if hasattr(st, 'session_state') and hasattr(st.session_state, 'polymer_chain_smiles_mapping'):
            if psmiles in st.session_state.polymer_chain_smiles_mapping:
                polymer_data = st.session_state.polymer_chain_smiles_mapping[psmiles]
                polymer_smiles = polymer_data['polymer_smiles']
                
                print(f"🧬 Found stored polymer chain SMILES for: {psmiles}")
                print(f"✅ Using polymer SMILES: {polymer_smiles[:60]}...")
                
                result.update({
                    'smiles': polymer_smiles,
                    'smiles_conversion_success': True,
                    'smiles_conversion_method': 'polymer_chain_from_DirectPolymerBuilder',
                    'conversion_metadata': {
                        'timestamp': datetime.now().isoformat(),
                        'source': 'DirectPolymerBuilder',
                        'candidate_id': polymer_data.get('candidate_id'),
                        'original_timestamp': polymer_data.get('timestamp'),
                        'description': 'Full polymer chain SMILES with end-caps from DirectPolymerBuilder'
                    }
                })
                return result
        
        # **PRIORITY 2: Monomer conversion fallback (NOT RECOMMENDED for final use)**
        if not self.converter:
            result['smiles_conversion_error'] = "No polymer chain SMILES found and PSMILESConverter not available"
            return result
            
        try:
            print(f"⚠️ No polymer chain SMILES found. Falling back to monomer conversion...")
            print(f"🧬 Converting monomer PSMILES to SMILES: {psmiles}")
            print(f"💡 NOTE: Consider building the polymer structure first for better SMILES representation")
            
            # Use the converter for monomer conversion
            smiles_result = self.converter.convert_psmiles_to_smiles(psmiles)
            
            if smiles_result['success'] and smiles_result['best_smiles']:
                result['smiles'] = smiles_result['best_smiles']
                result['smiles_conversion_success'] = True
                result['smiles_conversion_method'] = f"monomer_{smiles_result['best_method']}"
                result['conversion_metadata'] = {
                    'timestamp': datetime.now().isoformat(),
                    'source': 'monomer_fallback',
                    'all_methods_tried': list(smiles_result['conversions'].keys()),
                    'successful_methods': [
                        method for method, data in smiles_result['conversions'].items() 
                        if data.get('valid', False)
                    ],
                    'atom_count': smiles_result['conversions'].get(smiles_result['best_method'], {}).get('atoms', 'unknown'),
                    'conversion_description': 'Monomer SMILES with dummy atoms (not full polymer chain)',
                    'warning': 'This is monomer SMILES, not the final polymer chain SMILES'
                }
                print(f"✅ Monomer SMILES conversion: {result['smiles']} (method: {smiles_result['best_method']})")
                print(f"⚠️ This is monomer SMILES with dummy atoms, not the full polymer chain")
            else:
                result['smiles_conversion_error'] = smiles_result.get('error', 'Unknown conversion error')
                print(f"❌ Monomer SMILES conversion failed: {result['smiles_conversion_error']}")
                
        except Exception as e:
            result['smiles_conversion_error'] = str(e)
            print(f"❌ Exception during monomer SMILES conversion: {e}")
            
        return result
    
    def enhance_candidate_with_smiles(self, candidate: Dict[str, Any]) -> Dict[str, Any]:
        """
        Enhance a candidate with SMILES data using the stored PSMILES.
        
        Args:
            candidate: Candidate dictionary containing PSMILES
            
        Returns:
            Enhanced candidate with SMILES data
        """
        enhanced = candidate.copy()
        
        # Get PSMILES from candidate - try multiple possible keys
        psmiles = candidate.get('functionalized') or candidate.get('original') or candidate.get('psmiles')
        if not psmiles:
            enhanced.update({
                'smiles': None,
                'smiles_conversion_success': False,
                'smiles_conversion_error': 'No PSMILES found in candidate (checked: functionalized, original, psmiles keys)'
            })
            return enhanced
        
        # Store the PSMILES in the standard key for consistency
        enhanced['psmiles'] = psmiles
        
        # Convert and store SMILES
        smiles_data = self.convert_and_store_psmiles(psmiles)
        enhanced.update(smiles_data)
        
        return enhanced


def store_polymer_chain_smiles(psmiles: str, polymer_smiles: str, candidate_id: str = None) -> bool:
    """
    Store polymer chain SMILES generated from DirectPolymerBuilder for MD simulation use.
    
    This function updates the session state to map the original monomer PSMILES to 
    the actual polymer chain SMILES for MD simulation workflows.
    
    Args:
        psmiles: Original monomer PSMILES string
        polymer_smiles: Full polymer chain SMILES from DirectPolymerBuilder  
        candidate_id: Optional candidate identifier
        
    Returns:
        bool: True if successfully stored
    """
    try:
        print(f"🔗 Storing polymer chain SMILES for MD simulation:")
        print(f"   📝 Original PSMILES: {psmiles}")
        print(f"   🧬 Polymer SMILES: {polymer_smiles[:60]}...")
        print(f"   🆔 Candidate ID: {candidate_id}")
        
        # Initialize session state storage if needed
        if 'polymer_chain_smiles_mapping' not in st.session_state:
            st.session_state.polymer_chain_smiles_mapping = {}
        
        # Store the mapping from PSMILES to polymer chain SMILES
        st.session_state.polymer_chain_smiles_mapping[psmiles] = {
            'polymer_smiles': polymer_smiles,
            'candidate_id': candidate_id,
            'timestamp': datetime.now().isoformat(),
            'source': 'DirectPolymerBuilder'
        }
        
        # Also update any existing candidates in session state with this polymer SMILES
        if 'psmiles_candidates' in st.session_state:
            for candidate in st.session_state.psmiles_candidates:
                if candidate.get('psmiles') == psmiles:
                    # Update with polymer chain SMILES
                    candidate['polymer_smiles'] = polymer_smiles
                    candidate['polymer_smiles_source'] = 'DirectPolymerBuilder'
                    candidate['polymer_smiles_timestamp'] = datetime.now().isoformat()
                    print(f"   ✅ Updated candidate with polymer chain SMILES")
        
        print(f"✅ Polymer chain SMILES stored successfully for MD simulation use")
        return True
        
    except Exception as e:
        print(f"❌ Failed to store polymer chain SMILES: {e}")
        return False


def get_stored_smiles_for_psmiles(psmiles: str) -> Optional[str]:
    """
    Get stored SMILES for a PSMILES string from session candidates.
    
    **UPDATED**: Now prioritizes polymer chain SMILES over monomer SMILES for MD simulation.
    
    Args:
        psmiles: PSMILES string to find SMILES for
        
    Returns:
        SMILES string if found, None otherwise
    """
    # **NEW: First check for polymer chain SMILES mapping**
    if hasattr(st.session_state, 'polymer_chain_smiles_mapping'):
        polymer_mapping = st.session_state.polymer_chain_smiles_mapping.get(psmiles)
        if polymer_mapping:
            polymer_smiles = polymer_mapping['polymer_smiles']
            print(f"🎯 Found polymer chain SMILES for PSMILES: {polymer_smiles[:60]}...")
            return polymer_smiles
    
    # Fallback: Check candidates for any SMILES (monomer conversion)
    if hasattr(st.session_state, 'psmiles_candidates'):
        for candidate in st.session_state.psmiles_candidates:
            if candidate.get('psmiles') == psmiles:
                # Check if candidate has polymer chain SMILES
                if candidate.get('polymer_smiles'):
                    print(f"🎯 Found polymer chain SMILES in candidate: {candidate['polymer_smiles'][:60]}...")
                    return candidate['polymer_smiles']
                # Fallback to regular SMILES
                elif candidate.get('smiles'):
                    print(f"⚠️ Only found monomer SMILES, not polymer chain: {candidate['smiles']}")
                    return candidate['smiles']
            
    return None


def get_smiles_for_md_simulation(psmiles: str) -> Optional[str]:
    """
    Get SMILES string for MD simulation use. First tries stored polymer chain SMILES, 
    then falls back to conversion if needed.
    
    **UPDATED**: Now prioritizes polymer chain SMILES for MD simulation workflows.
    
    Args:
        psmiles: PSMILES string
        
    Returns:
        SMILES string for MD simulation use (preferably polymer chain SMILES)
    """
    # First try to get polymer chain SMILES from stored data
    stored_smiles = get_stored_smiles_for_psmiles(psmiles)
    if stored_smiles:
        # Check if this looks like a polymer chain (should be much longer than monomer)
        if len(stored_smiles) > 200:  # Polymer chains are typically much longer
            print(f"🎯 Using pre-stored polymer chain SMILES for MD simulation: {stored_smiles[:60]}...")
            return stored_smiles
        else:
            print(f"⚠️ Found stored SMILES but appears to be monomer, not polymer chain: {stored_smiles}")
        
    # Fallback to conversion (this will be monomer SMILES)
    print(f"⚠️ No polymer chain SMILES found, converting PSMILES to monomer SMILES for MD simulation")
    storage = PSMILESWithSMILESStorage()
    conversion_data = storage.convert_and_store_psmiles(psmiles)
    
    if conversion_data['smiles_conversion_success']:
        print(f"✅ Converted PSMILES to monomer SMILES for MD simulation: {conversion_data['smiles']}")
        print(f"⚠️ WARNING: Using monomer SMILES instead of polymer chain SMILES for MD simulation")
        return conversion_data['smiles']
    else:
        print(f"❌ Failed to convert PSMILES to SMILES for MD simulation: {conversion_data['smiles_conversion_error']}")
        return None
        

def update_session_candidates_with_smiles():
    """
    Update all session candidates with SMILES data if they don't have it.
    """
    if not hasattr(st.session_state, 'psmiles_candidates'):
        return
    
    storage = PSMILESWithSMILESStorage()
    updated_count = 0
    
    for candidate in st.session_state.psmiles_candidates:
        if candidate.get('psmiles') and not candidate.get('smiles'):
            print(f"🔄 Updating candidate with SMILES data...")
            smiles_data = storage.convert_and_store_psmiles(candidate['psmiles'])
            candidate.update(smiles_data)
            updated_count += 1
    
    if updated_count > 0:
        print(f"✅ Updated {updated_count} candidates with SMILES data")


def enhance_psmiles_generation_with_smiles_storage(generation_function, *args, **kwargs):
    """
    Enhance PSMILES generation function with automatic SMILES storage.
    
    This wrapper function automatically converts and stores SMILES for any PSMILES
    generated by the wrapped function.
    
    Args:
        generation_function: Function that generates PSMILES
        *args, **kwargs: Arguments to pass to the generation function
        
    Returns:
        Enhanced result with SMILES data included
    """
    # Call the original generation function
    result = generation_function(*args, **kwargs)
    
    # If generation was successful, enhance with SMILES
    if result and result.get('psmiles'):
        print(f"🧬 Enhancing PSMILES result with automatic SMILES conversion")
        
        storage = PSMILESWithSMILESStorage()
        smiles_data = storage.convert_and_store_psmiles(result['psmiles'])
        
        # Merge SMILES data into result
        result.update(smiles_data)
        
        # Also enhance any candidates if present
        if result.get('candidates'):
            enhanced_candidates = []
            for candidate in result['candidates']:
                if isinstance(candidate, str):  # If candidate is just a PSMILES string
                    candidate_dict = {'psmiles': candidate}
                    enhanced_candidate = storage.enhance_candidate_with_smiles(candidate_dict)
                    enhanced_candidates.append(enhanced_candidate)
                else:  # If candidate is already a dict
                    enhanced_candidate = storage.enhance_candidate_with_smiles(candidate)
                    enhanced_candidates.append(enhanced_candidate)
            result['candidates'] = enhanced_candidates
    
    return result 