#!/usr/bin/env python3
"""
PSMILES to SMILES Storage Utility

This module handles the conversion of PSMILES to full SMILES strings during generation
and ensures they are stored together for efficient MD simulation workflows.
"""

import streamlit as st
from typing import Dict, Optional, Any, List
from datetime import datetime
import traceback

# Import the converter
try:
    from utils.psmiles_to_smiles_converter import PSMILESConverter
    CONVERTER_AVAILABLE = True
except ImportError:
    CONVERTER_AVAILABLE = False


class PSMILESWithSMILESStorage:
    """Utility class to handle PSMILES generation with SMILES storage"""
    
    def __init__(self):
        self.converter = PSMILESConverter() if CONVERTER_AVAILABLE else None
        
    def convert_and_store_psmiles(self, psmiles: str) -> Dict[str, Any]:
        """
        Convert PSMILES to SMILES, prioritizing stored polymer chain SMILES.
        
        This method first checks for polymer chain SMILES generated by DirectPolymerBuilder.
        If found, it uses that. Otherwise, falls back to monomer conversion.
        
        Args:
            psmiles: PSMILES string to convert
            
        Returns:
            Dict containing both PSMILES and SMILES with conversion metadata
        """
        result = {
            'psmiles': psmiles,
            'smiles': None,
            'smiles_conversion_success': False,
            'smiles_conversion_method': None,
            'smiles_conversion_error': None,
            'conversion_metadata': {}
        }
        
        # **PRIORITY 1: Check for stored polymer chain SMILES**
        if hasattr(st, 'session_state') and hasattr(st.session_state, 'polymer_chain_smiles_mapping'):
            if psmiles in st.session_state.polymer_chain_smiles_mapping:
                polymer_data = st.session_state.polymer_chain_smiles_mapping[psmiles]
                polymer_smiles = polymer_data['polymer_smiles']
                
                print(f"🧬 Found stored polymer chain SMILES for: {psmiles}")
                print(f"✅ Using polymer SMILES: {polymer_smiles[:60]}...")
                
                result.update({
                    'smiles': polymer_smiles,
                    'smiles_conversion_success': True,
                    'smiles_conversion_method': 'polymer_chain_from_DirectPolymerBuilder',
                    'conversion_metadata': {
                        'timestamp': datetime.now().isoformat(),
                        'source': 'DirectPolymerBuilder',
                        'candidate_id': polymer_data.get('candidate_id'),
                        'original_timestamp': polymer_data.get('timestamp'),
                        'description': 'Full polymer chain SMILES with end-caps from DirectPolymerBuilder'
                    }
                })
                return result
        
        # **PRIORITY 2: Monomer conversion fallback (NOT RECOMMENDED for final use)**
        if not self.converter:
            result['smiles_conversion_error'] = "No polymer chain SMILES found and PSMILESConverter not available"
            return result
            
        try:
            print(f"⚠️ No polymer chain SMILES found. Falling back to monomer conversion...")
            print(f"🧬 Converting monomer PSMILES to SMILES: {psmiles}")
            print(f"💡 NOTE: Consider building the polymer structure first for better SMILES representation")
            
            # Use the converter for monomer conversion
            conversion_result = self.converter.convert_psmiles_to_smiles(psmiles)
            
            if conversion_result['success'] and conversion_result['best_smiles']:
                result['smiles'] = conversion_result['best_smiles']
                result['smiles_conversion_success'] = True
                result['smiles_conversion_method'] = f"monomer_{conversion_result['best_method']}"
                result['conversion_metadata'] = {
                    'timestamp': datetime.now().isoformat(),
                    'source': 'monomer_fallback',
                    'all_methods_tried': list(conversion_result['conversions'].keys()),
                    'successful_methods': [
                        method for method, data in conversion_result['conversions'].items() 
                        if data.get('valid', False)
                    ],
                    'atom_count': conversion_result['conversions'].get(conversion_result['best_method'], {}).get('atoms', 'unknown'),
                    'conversion_description': 'Monomer SMILES with dummy atoms (not full polymer chain)',
                    'warning': 'This is monomer SMILES, not the final polymer chain SMILES'
                }
                print(f"✅ Monomer SMILES conversion: {result['smiles']} (method: {conversion_result['best_method']})")
                print(f"⚠️ This is monomer SMILES with dummy atoms, not the full polymer chain")
            else:
                result['smiles_conversion_error'] = conversion_result.get('error', 'Unknown conversion error')
                print(f"❌ Monomer SMILES conversion failed: {result['smiles_conversion_error']}")
                
        except Exception as e:
            result['smiles_conversion_error'] = str(e)
            print(f"❌ Exception during monomer SMILES conversion: {e}")
            
        return result
    
    def enhance_candidate_with_smiles(self, candidate: Dict[str, Any]) -> Dict[str, Any]:
        """
        Enhance a PSMILES candidate dictionary with SMILES information.
        
        Args:
            candidate: Existing candidate dict with 'psmiles' key
            
        Returns:
            Enhanced candidate dict with SMILES information added
        """
        # Get PSMILES from candidate - try multiple possible keys
        psmiles = candidate.get('functionalized') or candidate.get('original') or candidate.get('psmiles')
        if not psmiles:
            print("⚠️ No PSMILES found in candidate (checked: functionalized, original, psmiles keys)")
            return candidate
            
        # Store the PSMILES in the standard key for consistency
        candidate['psmiles'] = psmiles
        
        # Convert PSMILES to SMILES
        conversion_data = self.convert_and_store_psmiles(psmiles)
        
        # Add SMILES data to candidate
        candidate.update(conversion_data)
        
        # Add timestamp for when SMILES was generated
        candidate['smiles_generated_at'] = datetime.now().isoformat()
        
        return candidate


def enhance_psmiles_generation_with_smiles_storage(
    generation_function,
    material_request: str, 
    *args, 
    **kwargs
) -> Dict[str, Any]:
    """
    Wrapper function to enhance any PSMILES generation function with SMILES storage.
    
    Args:
        generation_function: The original PSMILES generation function
        material_request: Material request string
        *args, **kwargs: Arguments to pass to generation function
        
    Returns:
        Enhanced result dict with SMILES included
    """
    # Initialize storage utility
    storage = PSMILESWithSMILESStorage()
    
    # Call original generation function
    print(f"🚀 Enhanced PSMILES generation with SMILES storage for: {material_request}")
    result = generation_function(material_request, *args, **kwargs)
    
    # Enhance result with SMILES
    if result and 'psmiles' in result:
        conversion_data = storage.convert_and_store_psmiles(result['psmiles'])
        result.update(conversion_data)
        
        # If we have candidates list, enhance each candidate
        if 'candidates' in result and isinstance(result['candidates'], list):
            enhanced_candidates = []
            for candidate in result['candidates']:
                if isinstance(candidate, str):
                    # Convert string PSMILES to dict format
                    candidate_dict = {'psmiles': candidate}
                    enhanced_candidate = storage.enhance_candidate_with_smiles(candidate_dict)
                    enhanced_candidates.append(enhanced_candidate)
                elif isinstance(candidate, dict) and 'psmiles' in candidate:
                    enhanced_candidate = storage.enhance_candidate_with_smiles(candidate.copy())
                    enhanced_candidates.append(enhanced_candidate)
                else:
                    enhanced_candidates.append(candidate)
            result['candidates'] = enhanced_candidates
            
        print(f"✅ Enhanced PSMILES generation completed with SMILES storage")
    else:
        print(f"⚠️ Could not enhance result - no PSMILES found")
        
    return result


def get_stored_smiles_for_psmiles(psmiles: str) -> Optional[str]:
    """
    Retrieve stored SMILES for a given PSMILES from session state candidates.
    
    Args:
        psmiles: PSMILES string to find SMILES for
        
    Returns:
        SMILES string if found, None otherwise
    """
    if 'psmiles_candidates' not in st.session_state:
        return None
        
    for candidate in st.session_state.psmiles_candidates:
        if candidate.get('psmiles') == psmiles and candidate.get('smiles'):
            print(f"✅ Found stored SMILES for PSMILES {psmiles}: {candidate['smiles']}")
            return candidate['smiles']
            
    return None


def get_smiles_for_md_simulation(psmiles: str) -> Optional[str]:
    """
    Get SMILES string for MD simulation use. First tries stored SMILES, 
    then falls back to conversion if needed.
    
    Args:
        psmiles: PSMILES string
        
    Returns:
        SMILES string for MD simulation use
    """
    # First try to get from stored candidates
    stored_smiles = get_stored_smiles_for_psmiles(psmiles)
    if stored_smiles:
        print(f"🎯 Using pre-stored SMILES for MD simulation: {stored_smiles}")
        return stored_smiles
        
    # Fallback to conversion
    print(f"⚠️ No stored SMILES found, converting PSMILES to SMILES for MD simulation")
    storage = PSMILESWithSMILESStorage()
    conversion_data = storage.convert_and_store_psmiles(psmiles)
    
    if conversion_data['smiles_conversion_success']:
        print(f"✅ Converted PSMILES to SMILES for MD simulation: {conversion_data['smiles']}")
        return conversion_data['smiles']
    else:
        print(f"❌ Failed to convert PSMILES to SMILES for MD simulation: {conversion_data['smiles_conversion_error']}")
        return None
        

def update_session_candidates_with_smiles():
    """
    Update existing session state candidates to include SMILES if not already present.
    This is a utility function for migrating existing data.
    """
    if 'psmiles_candidates' not in st.session_state:
        return
        
    storage = PSMILESWithSMILESStorage()
    updated_count = 0
    
    for i, candidate in enumerate(st.session_state.psmiles_candidates):
        if 'smiles' not in candidate or not candidate.get('smiles'):
            print(f"🔄 Adding SMILES to existing candidate {i}")
            enhanced_candidate = storage.enhance_candidate_with_smiles(candidate)
            st.session_state.psmiles_candidates[i] = enhanced_candidate
            updated_count += 1
            
    if updated_count > 0:
        print(f"✅ Updated {updated_count} existing candidates with SMILES")
    else:
        print(f"ℹ️ All existing candidates already have SMILES") 